const fs = require("fs");
const os = require("os");
const path = require("path");
const simpleGit = require("simple-git");
const { Octokit } = require("@octokit/rest");
const { app, BrowserWindow, ipcMain, dialog } = require("electron");
const {
  analyzeFile,
  analyzeProject,
  buildOpenApiDocFromRoutes,
  buildJsdocFromRoutes,
} = require("./core/analyzer");

let lastProjectAnalysis = null;

let githubToken = null;
let octokit = null;

const SETTINGS_FILE = () => path.join(app.getPath("userData"), "settings.json");

function loadSettings() {
  try {
    const p = SETTINGS_FILE();
    if (!fs.existsSync(p)) return {};
    return JSON.parse(fs.readFileSync(p, "utf-8"));
  } catch {
    return {};
  }
}

function saveSettings(settings) {
  const p = SETTINGS_FILE();
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(settings, null, 2), "utf-8");
}

function createWindow() {
  const win = new BrowserWindow({
    width: 1000,
    height: 700,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
    },
  });

  win.loadFile("index.html");
}

app.whenReady().then(() => {
  createWindow();

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});

ipcMain.handle("select-file", async () => {
  const { canceled, filePaths } = await dialog.showOpenDialog({
    properties: ["openFile"],
    filters: [{ name: "JavaScript", extensions: ["js", "jsx", "ts", "tsx"] }],
  });
  if (canceled || filePaths.length === 0) return null;
  return filePaths[0];
});

ipcMain.handle("analyze-file", async (_event, filePath) => {
  try {
    const model = analyzeFile(filePath);
    return model;
  } catch (e) {
    console.error(e);
    return { error: e.message };
  }
});

ipcMain.handle("select-project-dir", async () => {
  const { canceled, filePaths } = await dialog.showOpenDialog({
    properties: ["openDirectory"],
  });
  if (canceled || filePaths.length === 0) return null;
  return filePaths[0];
});

ipcMain.handle("analyze-project", async (_event, projectRoot) => {
  try {
    const result = analyzeProject(projectRoot);
    lastProjectAnalysis = result;
    saveSettings({ ...loadSettings(), lastLocalProjectDir: projectRoot });
    return result;
  } catch (e) {
    console.error(e);
    return { error: e.message };
  }
});

ipcMain.handle("export-doc", async (_, format) => {
  const routes = lastProjectAnalysis?.routes || [];

  if (!routes.length) {
    return { error: "No hay rutas analizadas" };
  }

  const { canceled, filePath } = await dialog.showSaveDialog({
    title: "Exportar documentación",
    defaultPath:
      format === "openapi" ? "openapi.json" : "routes.js",
    filters: [
      format === "openapi"
        ? { name: "OpenAPI", extensions: ["json"] }
        : { name: "JavaScript", extensions: ["js"] },
    ],
  });

  if (canceled || !filePath) return { canceled: true };

  if (format === "openapi") {
    const doc = buildOpenApiDocFromRoutes(routes, {
      title: "API generada automàticament",
      version: "1.0.0",
      serverUrl: "http://localhost:3000",
      descriptionByRouteFile: true,
    });

    fs.writeFileSync(filePath, JSON.stringify(doc, null, 2), "utf-8");
  } else {
    const jsdocText = buildJsdocFromRoutes(routes);

    const wrapped = `/**
 * @module API Routes
 * @description
 * Documentación de endpoints REST generada automáticamente
 * mediante análisis estático (AST) del código Express.
 *
 * AUTO-GENERATED FILE
 * Generated by TFG REST API Doc Generator
 */

${jsdocText}

module.exports = {};
`;

    fs.writeFileSync(filePath, wrapped, "utf-8");
  }

  return { filePath };
});

ipcMain.handle("github-set-token", async (_event, token) => {
  try {
    githubToken = token;
    saveSettings({ ...loadSettings(), githubToken: token });

    octokit = new Octokit({ auth: token });

    const { data } = await octokit.rest.users.getAuthenticated();
    return { ok: true, login: data.login };
  } catch (e) {
    console.error("Error validant token GitHub:", e.message);
    githubToken = null;
    octokit = null;
    return { ok: false, error: e.message };
  }
});

ipcMain.handle("github-list-repos", async () => {
  if (!octokit) {
    return { error: "No hi ha cap token de GitHub configurat." };
  }
  try {
    const res = await octokit.rest.repos.listForAuthenticatedUser({
      per_page: 100,
      sort: "updated",
    });
    const repos = res.data.map((r) => ({
      full_name: r.full_name,
      clone_url: r.clone_url,
      private: r.private,
    }));
    return { repos };
  } catch (e) {
    console.error("Error llistant repos:", e.message);
    return { error: e.message };
  }
});

ipcMain.handle("github-analyze-repo", async (_event, { fullName }) => {
  if (!octokit) {
    return { error: "GitHub no configurat." };
  }

  try {
    const baseTmpDir = path.join(os.tmpdir(), "tfg-docgen");
    if (!fs.existsSync(baseTmpDir)) fs.mkdirSync(baseTmpDir, { recursive: true });

    const localDir = path.join(
      baseTmpDir,
      fullName.replace("/", "_")
    );

    const git = simpleGit();

    const cloneUrl = `https://github.com/${fullName}.git`;

    if (!fs.existsSync(localDir)) {
      await git.clone(cloneUrl, localDir);
    } else {
      await simpleGit({ baseDir: localDir }).pull();
    }

    const result = analyzeProject(localDir);
    lastProjectAnalysis = result;
    saveSettings({ ...loadSettings(), lastGithubRepo: fullName });
    return result;
  } catch (e) {
    console.error("Error analitzant repo GitHub:", e);
    return { error: e.message };
  }
});

ipcMain.handle("settings-load", async () => {
  return loadSettings();
});

ipcMain.handle("settings-save", async (_event, patch) => {
  const current = loadSettings();
  const next = { ...current, ...patch };
  saveSettings(next);
  return { ok: true };
});
