const fs = require("fs");
const os = require("os");
const path = require("path");
const simpleGit = require("simple-git");
const { Octokit } = require("@octokit/rest");
const { app, BrowserWindow, ipcMain, dialog } = require("electron");
const { startSwaggerPreview } = require("./core/swaggerPreview");
const {
  analyzeFile,
  analyzeProject,
  buildOpenApiDocFromRoutes,
  buildJsdocFromRoutes,
} = require("./core/analyzer");

let lastProjectAnalysis = null;

let githubToken = null;
let octokit = null;

let swaggerPreview = null;
let swaggerPreviewWin = null;

const SETTINGS_FILE = () => path.join(app.getPath("userData"), "settings.json");

function loadSettings() {
  try {
    const p = SETTINGS_FILE();
    if (!fs.existsSync(p)) return {};
    return JSON.parse(fs.readFileSync(p, "utf-8"));
  } catch {
    return {};
  }
}

function saveSettings(settings) {
  const p = SETTINGS_FILE();
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(settings, null, 2), "utf-8");
}

function createWindow() {
  const win = new BrowserWindow({
    width: 1000,
    height: 700,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
    },
  });

  win.loadFile("index.html");
}

app.whenReady().then(() => {
  createWindow();

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});

ipcMain.handle("select-file", async () => {
  const { canceled, filePaths } = await dialog.showOpenDialog({
    properties: ["openFile"],
    filters: [{ name: "JavaScript", extensions: ["js", "jsx", "ts", "tsx"] }],
  });
  if (canceled || filePaths.length === 0) return null;
  return filePaths[0];
});

ipcMain.handle("analyze-file", async (_event, filePath) => {
  try {
    const model = analyzeFile(filePath);
    return model;
  } catch (e) {
    console.error(e);
    return { error: e.message };
  }
});

ipcMain.handle("select-project-dir", async () => {
  const { canceled, filePaths } = await dialog.showOpenDialog({
    properties: ["openDirectory"],
  });
  if (canceled || filePaths.length === 0) return null;
  return filePaths[0];
});

ipcMain.handle("analyze-project", async (_event, projectRoot) => {
  try {
    const settings = loadSettings();

    const folderWhitelist = Array.isArray(settings.folderWhitelist)
      ? settings.folderWhitelist
      : [];

    const result = analyzeProject(projectRoot, {
      folderWhitelist,
    });

    lastProjectAnalysis = result;

    saveSettings({
      ...settings,
      lastLocalProjectDir: projectRoot,
    });

    return result;
  } catch (e) {
    console.error(e);
    return { error: e.message };
  }
});

ipcMain.handle("export-doc", async (_, format) => {
  const routes = lastProjectAnalysis?.routes || [];

  if (!routes.length) {
    return { error: "No hay rutas analizadas" };
  }

  const { canceled, filePath } = await dialog.showSaveDialog({
    title: "Exportar documentación",
    defaultPath:
      format === "openapi" ? "openapi.json" : "routes.js",
    filters: [
      format === "openapi"
        ? { name: "OpenAPI", extensions: ["json"] }
        : { name: "JavaScript", extensions: ["js"] },
    ],
  });

  if (canceled || !filePath) return { canceled: true };

  if (format === "openapi") {
    const doc = buildOpenApiDocFromRoutes(routes, {
      title: "API generada automàticament",
      version: "1.0.0",
      serverUrl: "http://localhost:3000",
      descriptionByRouteFile: true,
    });

    fs.writeFileSync(filePath, JSON.stringify(doc, null, 2), "utf-8");
  } else {
    const jsdocText = buildJsdocFromRoutes(routes);

    const wrapped = `/**
 * @module API Routes
 * @description
 * Documentación de endpoints REST generada automáticamente
 * mediante análisis estático (AST) del código Express.
 *
 * AUTO-GENERATED FILE
 * Generated by TFG REST API Doc Generator
 */

${jsdocText}

module.exports = {};
`;

    fs.writeFileSync(filePath, wrapped, "utf-8");
  }

  return { filePath };
});

ipcMain.handle("github-set-token", async (_event, token) => {
  try {
    githubToken = token;
    saveSettings({ ...loadSettings(), githubToken: token });

    octokit = new Octokit({ auth: token });

    const { data } = await octokit.rest.users.getAuthenticated();
    return { ok: true, login: data.login };
  } catch (e) {
    console.error("Error validant token GitHub:", e.message);
    githubToken = null;
    octokit = null;
    return { ok: false, error: e.message };
  }
});

ipcMain.handle("github-list-repos", async () => {
  if (!octokit) {
    return { error: "No hi ha cap token de GitHub configurat." };
  }
  try {
    const res = await octokit.rest.repos.listForAuthenticatedUser({
      per_page: 100,
      sort: "updated",
    });
    const repos = res.data.map((r) => ({
      full_name: r.full_name,
      clone_url: r.clone_url,
      private: r.private,
    }));
    return { repos };
  } catch (e) {
    console.error("Error llistant repos:", e.message);
    return { error: e.message };
  }
});

ipcMain.handle("github-analyze-repo", async (_, payload) => {
  try {
    if (!octokit) {
      return { error: "GitHub no conectado. Guarda y prueba el token." };
    }

    const settings = loadSettings();

    const folderWhitelist = Array.isArray(settings.folderWhitelist)
      ? settings.folderWhitelist
      : [];

    const { fullName, branch } = payload || {};
    const [owner, repo] = (fullName || "").split("/");
    if (!owner || !repo) {
      return { error: "Formato de repo inválido (owner/repo)" };
    }

    let finalBranch = branch;
    if (!finalBranch) {
      const repoInfo = await octokit.repos.get({ owner, repo });
      finalBranch = repoInfo.data.default_branch;
    }

    const reposBaseDir = path.join(app.getPath("userData"), "repos");
    if (!fs.existsSync(reposBaseDir)) {
      fs.mkdirSync(reposBaseDir, { recursive: true });
    }

    const localRepoDir = path.join(reposBaseDir, `${owner}__${repo}`);
    const git = simpleGit();
    const remoteUrl = `https://github.com/${owner}/${repo}.git`;

    if (!fs.existsSync(localRepoDir)) {
      await git.clone(remoteUrl, localRepoDir);
    }

    const repoGit = simpleGit(localRepoDir);

    await repoGit.fetch(["--all", "--prune"]);

    const branches = await repoGit.branch(["-a"]);
    const localExists = branches.all.includes(finalBranch);
    const remoteExists = branches.all.includes(`remotes/origin/${finalBranch}`);

    if (!localExists) {
      if (!remoteExists) {
        return { error: `La rama "${finalBranch}" no existe en origin.` };
      }
      await repoGit.checkout(["-b", finalBranch, `origin/${finalBranch}`]);
    } else {
      await repoGit.checkout(finalBranch);
    }

    await repoGit.pull("origin", finalBranch);

    const result = analyzeProject(localRepoDir, {
      folderWhitelist,
    });

    lastProjectAnalysis = result;

    return {
      ...result,
      repo: fullName,
      branch: finalBranch,
      folderWhitelist,
    };
  } catch (e) {
    console.error(e);
    return { error: e.message || String(e) };
  }
});

ipcMain.handle("settings-load", async () => {
  return loadSettings();
});

ipcMain.handle("settings-save", async (_event, patch) => {
  const current = loadSettings();
  const next = { ...current, ...patch };
  saveSettings(next);
  return { ok: true };
});

ipcMain.handle("github-list-branches", async (_, fullName) => {
  try {
    if (!octokit) return { error: "GitHub no conectado. Guarda y prueba el token." };

    const [owner, repo] = fullName.split("/");
    if (!owner || !repo) return { error: "Formato de repo inválido (owner/repo)" };

    const repoInfo = await octokit.repos.get({ owner, repo });
    const defaultBranch = repoInfo.data.default_branch;

    const branchesRes = await octokit.repos.listBranches({
      owner,
      repo,
      per_page: 100,
    });

    return {
      defaultBranch,
      branches: branchesRes.data.map((b) => ({ name: b.name })),
    };
  } catch (e) {
    return { error: e.message || String(e) };
  }
});

ipcMain.handle("preview-swagger", async () => {
  const routes = lastProjectAnalysis?.routes || [];
  if (!routes.length) return { error: "No hay rutas analizadas" };

  if (swaggerPreviewWin && !swaggerPreviewWin.isDestroyed()) {
    swaggerPreviewWin.focus();
    return { ok: true };
  }

  swaggerPreview = await startSwaggerPreview(() => {
    return buildOpenApiDocFromRoutes(routes, {
      title: "API generada automàticament",
      version: "1.0.0",
      serverUrl: "http://localhost:3000",
      descriptionByRouteFile: true,
    });
  });

  swaggerPreviewWin = new BrowserWindow({
    width: 1200,
    height: 800,
    title: "Previsualización Swagger",
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  await swaggerPreviewWin.loadURL(swaggerPreview.url);

  swaggerPreviewWin.on("closed", async () => {
    swaggerPreviewWin = null;
    if (swaggerPreview) {
      await swaggerPreview.stop();
      swaggerPreview = null;
    }
  });

  return { ok: true };
});